#! /bin/zsh
DIR=~/dotfiles
cp $DIR/bin/update_arch $DIR/bin/update

sudo ln -sf $DIR/pacman/pacman.conf /etc/
sudo ln -sf $DIR/pacman/mirrorlist /etc/pacman.d/

 for testing purpose
$DIR/bin/update

sudo pacman -Sy \
    docker\
    docker-compose\
    brave\
    synapse\
    termite\
    wicd\
;

ln -sf $DIR/vim/.vimrc ~/

ln -sf $DIR/i3/config ~/.i3/
ln -sf $DIR/i3/i3status.conf ~/.i3/

mkdir -p ~/.config/termite
ln -sf $DIR/termite/config ~/.config/termite
ln -sf $DIR/ranger ~/.config/ranger

ln -sf $DIR/bin ~/

ln -sf $DIR/X11/.xinitrc ~/.xinitrc
