#! /bin/zsh
DIR=~/dotfiles
cp $DIR/bin/update_arch $DIR/bin/update

sudo ln -sf $DIR/pacman/pacman.conf /etc/
sudo ln -sf $DIR/pacman/mirrorlist /etc/pacman.d/

 for testing purpose
$DIR/bin/update

sudo pacman -Sy \
    docker\
    docker-compose\
    brave\
    rofi\
    alacritty\
    wicd\
;

ln -sf $DIR/vim/.vimrc ~/

ln -sf $DIR/i3 ~/.i3

ln -sf $DIR/sway ~/.config/sway

ln -sf $DIR/alacritty ~/.config/alacritty

ln -sf $DIR/ranger ~/.config/ranger

ln -sf $DIR/rofi ~/.config/rofi

ln -sf $DIR/dunst ~/.config/dunst

ln -sf $DIR/bin ~/

ln -sf $DIR/X11/.xinitrc ~/.xinitrc
